apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  selector:
    matchLabels:
      app: example-service
  replicas: 2
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
        - name: example-service
          image: registry.hub.docker.com/alvarosanchez/example-service
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example-service
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
